Repository HaxeFlixel/flixel, pull requests merged in 2018-04, with the labels that each got.

#2138 FlxObject: fix for getting stuck on y-axis collisions, closes #1566
  flixel/FlxObject.hx
Labels: Bug, Collisions

#2139 FlxBar: rounding value of filled bar
  flixel/ui/FlxBar.hx
Labels: Bug

#2136 Add support for OpenFL 8
  .travis.yml
  assets/templates/html5/index.html
  flixel/FlxCamera.hx
  flixel/FlxGame.hx
  flixel/graphics/FlxGraphic.hx
  flixel/graphics/tile/FlxDrawBaseItem.hx
  flixel/graphics/tile/FlxDrawQuadsItem.hx
  flixel/graphics/tile/FlxDrawTilesItem.hx
  flixel/graphics/tile/FlxDrawTrianglesItem.hx
  flixel/graphics/tile/FlxGraphicsShader.hx
  flixel/graphics/tile/FlxTilesheet.hx
  flixel/system/FlxAssets.hx
  flixel/system/FlxBasePreloader.hx
  flixel/system/FlxPreloader.hx
  flixel/system/FlxSound.hx
  flixel/system/debug/completion/CompletionList.hx
  flixel/system/debug/console/Console.hx
  flixel/system/debug/interaction/Interaction.hx
  flixel/system/debug/log/Log.hx
  flixel/system/debug/log/LogStyle.hx
  flixel/system/debug/stats/Stats.hx
  flixel/system/frontEnds/BitmapFrontEnd.hx
  flixel/system/frontEnds/LogFrontEnd.hx
  flixel/system/frontEnds/SoundFrontEnd.hx
  flixel/system/macros/FlxDefines.hx
  flixel/text/FlxText.hx
  haxelib.json
  include.xml
  tests/RunTravis.hx
  tests/swfVersion/11/source/Main.hx
  tests/swfVersion/11_2/source/Main.hx
Labels: OpenFL / Lime

#2146 FlxSpriteGroup: add camera setter override, closes #2144
  flixel/group/FlxSpriteGroup.hx
Labels: Improvement
