Repository HaxeFlixel/flixel, pull requests merged in 2024-02, with the labels that each got.

#3025 warn or ignore certain missing xml elements
  flixel/graphics/frames/bmfont/BMFont.hx
  flixel/graphics/frames/bmfont/BMFontChar.hx
  flixel/graphics/frames/bmfont/BMFontCommon.hx
  flixel/graphics/frames/bmfont/BMFontInfo.hx
  flixel/graphics/frames/bmfont/BMFontKerning.hx
  flixel/graphics/frames/bmfont/BMFontPage.hx
  flixel/graphics/frames/bmfont/BMFontXml.hx
Labels: Bug, Regression

#3027 Added `letterSpacing` variable to `FlxText`.
  flixel/text/FlxText.hx
Labels: New Feature

#3037 Honor scale in FlxBitmapText width and height, add setCharFrame
  flixel/graphics/frames/FlxBitmapFont.hx
  flixel/text/FlxBitmapText.hx
Labels: Text

#3040 Add FlxTimer.wait and FlxTimer.loop
  flixel/util/FlxTimer.hx
  tests/unit/src/flixel/util/FlxTimerTest.hx
Labels: Improvement, New Feature
