Repository HaxeFlixel/flixel, pull requests merged in 2024-03, with the labels that each got.

#3063 FlxCamera.stopFade, stopFlash, and stopShake
  flixel/FlxCamera.hx
Labels: Improvement

#3065 Remove (now redundant) health variable and function in FlxObject
  flixel/FlxObject.hx
Labels: Breaking Change

#3068 simplify cameras in FlxSpriteContainer, fix FlxStrip/FlxBitmapText
  flixel/FlxStrip.hx
  flixel/group/FlxSpriteContainer.hx
  flixel/text/FlxBitmapText.hx
Labels: Improvement

#3069 add rect.containsXY move logic from FlxMath
  flixel/math/FlxMath.hx
  flixel/math/FlxRect.hx
Labels: New Feature

#3070 add flixel-ui defines
  flixel/system/macros/FlxDefines.hx
Labels: Structure, CI

#2907 Default zoom
  flixel/FlxCamera.hx
  flixel/system/frontEnds/CameraFrontEnd.hx
Labels: Breaking Change

#3072 Replace references to FlxG.camera with this.getDefaultCamera
  flixel/FlxBasic.hx
  flixel/FlxObject.hx
  flixel/FlxSprite.hx
  flixel/path/FlxPath.hx
  flixel/tile/FlxBaseTilemap.hx
  flixel/tile/FlxTilemap.hx
  flixel/util/FlxSpriteUtil.hx
Labels: Breaking Change, Camera

#3087 Add disabled status to FlxButton
  assets/images/ui/button.png
  flixel/ui/FlxButton.hx
  tests/unit/src/flixel/ui/FlxButtonTest.hx
Labels: New Feature, Input
