Repository HaxeFlixel/flixel, pull requests merged in 2024-11, with the labels that each got.

#3280 FlxGamepadManager: Add FlxG.gamepads.acceptMode
  flixel/input/gamepad/FlxGamepad.hx
  flixel/input/gamepad/FlxGamepadAnalogStick.hx
  flixel/input/gamepad/FlxGamepadManager.hx
  flixel/input/gamepad/FlxGamepadMappedInput.hx
  flixel/input/gamepad/id/LogitechID.hx
  flixel/input/gamepad/id/MFiID.hx
  flixel/input/gamepad/id/MayflashWiiRemoteID.hx
  flixel/input/gamepad/id/OUYAID.hx
  flixel/input/gamepad/id/PS4ID.hx
  flixel/input/gamepad/id/PSVitaID.hx
  flixel/input/gamepad/id/SwitchJoyconLeftID.hx
  flixel/input/gamepad/id/SwitchJoyconRightID.hx
  flixel/input/gamepad/id/SwitchProID.hx
  flixel/input/gamepad/id/WiiRemoteID.hx
  flixel/input/gamepad/id/XInputID.hx
  flixel/input/gamepad/mappings/FlxGamepadMapping.hx
  flixel/input/gamepad/mappings/LogitechMapping.hx
  flixel/input/gamepad/mappings/MFiMapping.hx
  flixel/input/gamepad/mappings/MayflashWiiRemoteMapping.hx
  flixel/input/gamepad/mappings/OUYAMapping.hx
  flixel/input/gamepad/mappings/PS4Mapping.hx
  flixel/input/gamepad/mappings/PSVitaMapping.hx
  flixel/input/gamepad/mappings/SwitchJoyconLeftMapping.hx
  flixel/input/gamepad/mappings/SwitchJoyconRightMapping.hx
  flixel/input/gamepad/mappings/SwitchProMapping.hx
  flixel/input/gamepad/mappings/WiiRemoteMapping.hx
  flixel/input/gamepad/mappings/XInputMapping.hx
Labels: Improvement, Input

#3279 Stricter checks for FlxG.bitmap.maxTextureSize
  flixel/graphics/FlxGraphic.hx
  flixel/system/frontEnds/BitmapFrontEnd.hx
  flixel/system/macros/FlxDefines.hx
Labels: Improvement, Structure

#2982 FlxG.assets: A way to overwrite and customize the way HaxeFlixel fetches or produces assets from ids
  flixel/FlxG.hx
  flixel/graphics/FlxGraphic.hx
  flixel/graphics/frames/FlxAtlasFrames.hx
  flixel/input/mouse/FlxMouse.hx
  flixel/sound/FlxSound.hx
  flixel/system/FlxAssets.hx
  flixel/system/FlxSplash.hx
  flixel/system/frontEnds/AssetFrontEnd.hx
  flixel/system/frontEnds/BitmapFrontEnd.hx
  flixel/system/frontEnds/LogFrontEnd.hx
  flixel/system/frontEnds/SoundFrontEnd.hx
  flixel/system/macros/FlxDefines.hx
  flixel/system/ui/FlxSoundTray.hx
  flixel/text/FlxText.hx
  flixel/tile/FlxBaseTilemap.hx
  flixel/util/FlxStringUtil.hx
Labels: New Feature, Structure, Assets

#3286 FlxSave: Allow custom handling of parsing errors
  flixel/util/FlxSave.hx
Labels: Improvement, New Feature, Saving

#3295 Check if maxTextureSize >0 rather than !=-1
  flixel/graphics/FlxGraphic.hx
Labels: Bug

#3296 fix custom asset path, add _abs
  flixel/system/frontEnds/AssetFrontEnd.hx
  flixel/system/macros/FlxDefines.hx
Labels: Bug, Assets
