Repository HaxeFlixel/flixel, pull requests merged in 2024-12, with the labels that each got.

#3271 Stop dispatching onFocus event when closing debugger
  flixel/system/frontEnds/DebuggerFrontEnd.hx
Labels: Improvement

#3303 FlxDirectionFlags: add up, down, left and right fields
  flixel/util/FlxDirectionFlags.hx
Labels: New Feature

#3306 fix list
  flixel/system/frontEnds/AssetFrontEnd.hx
Labels: Assets

#3307 replace callback with onLog
  CHANGELOG.md
  flixel/system/debug/log/LogStyle.hx
  flixel/system/frontEnds/LogFrontEnd.hx
Labels: New Feature, FlxDebugger

#3314 Automatically append file extension to sound asset ids
  flixel/sound/FlxSound.hx
  flixel/system/frontEnds/AssetFrontEnd.hx
  flixel/system/frontEnds/SoundFrontEnd.hx
  flixel/system/macros/FlxDefines.hx
  tests/coverage/Project.xml
Labels: New Feature, Assets

#3313 Update outdated documentation for BitmapFrontEnd.
  flixel/system/frontEnds/BitmapFrontEnd.hx
Labels: Documentation

#3321 Fix camera.color
  flixel/graphics/tile/FlxDrawQuadsItem.hx
  flixel/graphics/tile/FlxDrawTrianglesItem.hx
  flixel/graphics/tile/FlxGraphicsShader.hx
Labels: Rendering

#3326 fix camera.color
  flixel/graphics/tile/FlxGraphicsShader.hx
Labels: Rendering
