Repository HaxeFlixel/flixel, pull requests merged in 2024-04, with the labels that each got.

#3035 Add kerning to bitmap fonts created from BMFont files
  flixel/graphics/frames/FlxBitmapFont.hx
  flixel/graphics/frames/bmfont/BMFont.hx
  flixel/text/FlxBitmapText.hx
  tests/unit/src/flixel/graphics/frames/bmfont/BMFontTest.hx
Labels: Text

#3108 fix pooling in cameras following
  flixel/FlxCamera.hx
  flixel/util/FlxPool.hx
Labels: performance

#2863 update transform after setting pan
  flixel/sound/FlxSound.hx
Labels: OpenFL / Lime, Sound

#3113 Quick patch
  CHANGELOG.md
  flixel/graphics/frames/FlxImageFrame.hx
  flixel/group/FlxSpriteGroup.hx
  haxelib.json
Labels: Bug

#3116 better long term solution for sprite group cameras
  CHANGELOG.md
  flixel/group/FlxSpriteGroup.hx
  haxelib.json
Labels: Bug, Regression

#3120 Fix wrap without reverting kerning
  flixel/graphics/frames/FlxBitmapFont.hx
  flixel/text/FlxBitmapText.hx
  tests/unit/src/flixel/text/FlxBitmapTextTest.hx
Labels: Bug, New Feature, Text

#3119 Fix `FlxKey` maps not containing `FlxKey.NONE`
  flixel/input/keyboard/FlxKey.hx
Labels: Improvement
