Repository HaxeFlixel/flixel, pull requests merged in 2024-06, with the labels that each got.

#3125 account for scale, origin, offset, angle and pixelPerfectPosition in getGraphicMidpoint
  flixel/FlxSprite.hx
  flixel/math/FlxRect.hx
  tests/unit/src/flixel/FlxSpriteTest.hx
Labels: Improvement, New Feature

#3158 Major change to FlxTilemap/FlxTiles Improve collision, debug drawing, add various features
  flixel/FlxObject.hx
  flixel/math/FlxRect.hx
  flixel/path/FlxPathfinder.hx
  flixel/tile/FlxBaseTilemap.hx
  flixel/tile/FlxTile.hx
  flixel/tile/FlxTilemap.hx
  haxelib.json
  tests/coverage/Project.xml
  tests/unit/src/flixel/FlxObjectTest.hx
  tests/unit/src/flixel/path/FlxPathTest.hx
  tests/unit/src/flixel/tile/FlxTilemapTest.hx
Labels: Improvement, Bug, New Feature, Structure, Testing

#3183 Add trackingInfo to FlxGraphic for debugging
  flixel/FlxSprite.hx
  flixel/graphics/FlxGraphic.hx
  flixel/system/macros/FlxDefines.hx
  flixel/text/FlxText.hx
Labels: New Feature, FlxDebugger

#3184 ignore alpha when point-selecting sprites
  flixel/system/debug/interaction/Interaction.hx
Labels: Improvement, FlxDebugger

#3179 Implement FlxFlicker.pause() and FlxFlicker.resume()
  flixel/effects/FlxFlicker.hx
Labels: New Feature

#3190 Fix rect.intersections, add rect.clipTo
  flixel/math/FlxRect.hx
  tests/unit/src/flixel/math/FlxRectTest.hx
Labels: Bug, New Feature

#3193 Ignore border outline when computing field size
  flixel/text/FlxBitmapText.hx
Labels: Text

#3194 Fix crashes from negative tiles
  flixel/tile/FlxTilemap.hx
  tests/unit/src/flixel/tile/FlxTilemapTest.hx
Labels: Regression
