Repository HaxeFlixel/flixel, pull requests merged in 2025-02, with the labels that each got.

#3362 GC-Free group iterator
  flixel/group/FlxGroup.hx
Labels: Improvement

#3365 Fix distanceTo regression in FlxPoint
  flixel/math/FlxPoint.hx
  tests/unit/src/flixel/math/FlxPointTest.hx
Labels: Bug

#3370 fix flash camera size
  flixel/FlxCamera.hx
Labels: Bug, Target-Flash, Regression

#3369 Query max texture size only once instead of every time it's needed.
  flixel/system/frontEnds/BitmapFrontEnd.hx
Labels: Structure, Rendering

#3375 Improve debug windows
  flixel/system/debug/ScrollSprite.hx
  flixel/system/debug/interaction/Interaction.hx
  flixel/system/debug/interaction/tools/LogBitmap.hx
  flixel/system/debug/interaction/tools/TrackObject.hx
  flixel/system/debug/watch/EditableTextField.hx
  flixel/system/debug/watch/Watch.hx
  flixel/system/debug/watch/WatchEntry.hx
  flixel/system/frontEnds/BitmapLogFrontEnd.hx
  flixel/system/frontEnds/DebuggerFrontEnd.hx
  flixel/system/frontEnds/WatchFrontEnd.hx
Labels: FlxDebugger

#3376 Refactor debug windows
  flixel/system/debug/interaction/Interaction.hx
  flixel/system/debug/interaction/tools/Pointer.hx
  flixel/system/debug/interaction/tools/Transform.hx
  flixel/system/debug/log/BitmapLog.hx
Labels: Improvement, FlxDebugger

#3382 FlxRect: Add FlxReadOnlyRect and setAbs/setBounds
  flixel/math/FlxRect.hx
Labels: New Feature

#3378 Add custom text option to FlxSoundTray
  flixel/system/frontEnds/SoundFrontEnd.hx
  flixel/system/ui/FlxSoundTray.hx
Labels: New Feature, Sound
