Repository HaxeFlixel/flixel, pull requests merged in 2025-10, with the labels that each got.

#3500 Fix riding moving platforms
  flixel/FlxObject.hx
  tests/unit/src/flixel/FlxObjectTest.hx
Labels: Bug, Regression, Collisions

#3504 `FlxTilemap`: Fix debug draw when zoomed
  flixel/tile/FlxTilemap.hx
Labels: Bug, Rendering, FlxDebugger, Regression

#3506 Fixed watch window position
  flixel/system/debug/FlxDebugger.hx
Labels: Bug, FlxDebugger
