Repository HaxeFlixel/flixel, pull requests merged in 2025-09, with the labels that each got.

#3476 Update uv in frame.clip()
  flixel/graphics/frames/FlxFrame.hx
  tests/unit/src/flixel/graphics/frames/FlxFrameTest.hx
Labels: Bug, Rendering

#3484 Fix FlxStrip disapearing on zoomed out cameras
  flixel/FlxCamera.hx
Labels: Bug, Rendering, Camera

#3485 add unit tests for #3436
  tests/unit/src/flixel/util/FlxSignalTest.hx
Labels: CI, Github

#3462 FlxDrawQuadsItem: call endFill() after drawing
  flixel/graphics/tile/FlxDrawQuadsItem.hx
Labels: Improvement, Rendering, Camera

#3449 Improve zoomed debug hitboxes performance
  flixel/FlxObject.hx
Labels: Improvement, Rendering, FlxDebugger, Performance/Memory
